<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [109]:
import numpy as np
import pandas as pd

In [110]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    array = np.arange(1,n+1)
    return array.prod()





In [111]:
factorial(5)

120

In [112]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    array = np.arange(1,n+1)
    return array.cumprod()

In [113]:
all_factorials(5)

array([  1,   2,   6,  24, 120], dtype=int32)

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [117]:
def get_pct_changes(file_name):
    price_data = np.genfromtxt(file_name, delimiter=",", missing_values="null", skip_header=1)[:,1]
    final_price_data = price_data[~np.isnan(price_data)]

    return np.diff(final_price_data)/final_price_data[:-1]

In [121]:
get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

In [119]:
# to check if same result
apple = pd.read_csv('apple.csv')
apple['change'] = apple['Adj Close'].pct_change()
apple
# apple['change'] has same values to get_pct_changes('apple.csv')

Date   Adj Close    change
0     1980-12-12    0.421597       NaN
1     1980-12-15    0.399601 -0.052173
2     1980-12-16    0.370272 -0.073396
3     1980-12-17    0.379437  0.024752
4     1980-12-18    0.390436  0.028988
...          ...         ...       ...
9273  2017-09-20  156.070007 -0.016758
9274  2017-09-21  153.389999 -0.017172
9275  2017-09-22  151.889999 -0.009779
9276  2017-09-25  150.550003 -0.008822
9277  2017-09-26  153.139999  0.017204

[9278 rows x 3 columns]

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [138]:
datafile = "apple.csv"
import pandas as pd
df = pd.read_csv(datafile,na_values='null')

df['change'] = df['Adj Close'].pct_change()

def categorize(x):
    output = ""
    if np.isnan(x):
        output = np.nan
    elif x>0.025: 
        output = "High+"
    elif x>0:
        output = "Low+"
    elif x>=-0.025:
        output = "Low-"
    else:
        output = "High-"
    return output
        
grouped = df.groupby(lambda x: categorize(df.iloc[x,2]))
print(grouped.size())
print(grouped.mean())

High+    1391
High-    1210
Low+     3170
Low-     3506
dtype: int64
       Adj Close    change
High+   8.652295  0.045705
High-   8.289065 -0.044220
Low+   26.292799  0.011020
Low-   21.827111 -0.010005
